server.port=8080



spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hikari tuning for Supabase free tier
spring.datasource.hikari.maximum-pool-size=6
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.jpa.open-in-view=false

# here is redis cache configuration

spring.data.redis.host=${UPSTASH_HOST}
spring.data.redis.port=6379
spring.data.redis.password=${UPSTASH_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=6000ms
spring.data.redis.connect-timeout=6000ms

# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

# Spring Boot default is 1MB – increase it:
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB



spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


# here is google cloudinary configuration
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}


CLOUDINARY_URL=cloudinary://<your_api_key>:<your_api_secret>@dypxgh3ut

