
spring.application.name=OnlineBookStoreRestfullApi

spring.profiles.active=prod

# ================= DATABASE =================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Spring keeps DB session open during request rendering.
spring.jpa.open-in-view=false

# Hikari tuning for Supabase free tier
spring.datasource.hikari.maximum-pool-size=6
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update

# ================= JWT CONFIG =================

jwt.key=${JWT_SECRET}

jwt.issuer=online-book-store

access.ttl.seconds=987
refresh.ttl.seconds=60898900

jwt.cookie.name=refreshToken
jwt.cookie.secure=false
jwt.cookie.http.only=true
jwt.cookie.same.site=lax
jwt.cookie.domain=

# ================= RAZORPAY =================

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# ================= FILE UPLOAD =================

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# ================= CLOUDINARY =================

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

CLOUDINARY_URL=cloudinary://<your_api_key>:<your_api_secret>@dypxgh3ut